name: actvity types
on:
  workflow_dispatch:
  push:
    types:
      - opened
      - edited
jobs:
  test-types:
    runs-on: ubuntu-lates
    steps:
     - name: test types
       run: echo "testing types of activity in even github"
