name: test for artifacts
on:
  workflow_dispatch:
jobs:
  artifacts-test:
    runs-on: ubuntu-latest
    steps:
      - name: test-artifaacts
        run: echo "test"
      - name: test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test.yaml
      
